### ISSUE TITLE
middleman?

### ISSUE THREAD

**Issue by mraaroncruz** [rossconf/rossconf.io#1]
Should we make this a middleman project?
middleman [site](http://middlemanapp.com) and [repo](https://github.com/middleman/middleman)

Yes? Ok. I can do it if I get some plus einses.
## 

alles liebe,
kreutz

**Comment by FloorD** [comment]
:+eins:

**Comment by ShellyCoen** [comment]
+1

**Comment by mraaroncruz** [comment]
see pull request #2
