### ISSUE TITLE
Find date in September for ROSS Conf Berlin

### ISSUE THREAD

**Issue by FloorD** [rossconf/rossconf.io#15]
Find date in September for ROSS Conf Berlin that does not conflict with other conferences (like BaRuCo - 1-5 September).

**Comment by mraaroncruz** [comment]
I just asked about this in the chat. I will look into it

**Comment by alicetragedy** [comment]
RubyConf Portugal is on the 14-15 September, might also be a no-no.

**Comment by mraaroncruz** [comment]
There doesn't seem to be anything going on in Europe on the weekend of the 25th of September.

Rocky Mountain is happening at the same time but I don't think we can avoid all conflicts and it is really far away http://www.rockymtnruby.com/

**Comment by mraaroncruz** [comment]
I agree with @alicetragedy plus I want to go to that one :dancer:

**Comment by mraaroncruz** [comment]
http://rubyconferences.org/

**Comment by alicetragedy** [comment]
I'm not sure yet which ones I'm going to, but I will be going on holiday at some point beginning of September to enjoy a hopefully tourist-less beach in Italy .. So end of September as @pferdefleisch suggested sounds perfect to me. Also, I don't necessarily have to come :trollface:

**Comment by FloorD** [comment]
September 26th it is :bowtie:

**Comment by bastilian** [comment]
Closing as date is set and event page is online.
