### ISSUE TITLE
Create berlin.rossconf.io / rossconf.io/berlin WIP

### ISSUE THREAD

**Issue by FloorD** [rossconf/rossconf.io#16]
Create berlin.rossconf.io or rossconf.io/berlin with the following partials:

**Intro:**
ROSS Conf is a one day mini-conference bringing Open Source Software maintainers and developers together in one room. Or in multiple rooms, to be fair. The projects participating in its second edition include Ruby Core (Zachary Scott) and XX. In the morning bit the project owners will introduce their projects and share what would need work in the afternoon hackathon-y part.

We ask for a deposit which you will get back upon attendance.

**Testimonials:**
Katrina Owen: "ROSSConf was brilliant. 28 PRs from 9 different people, several bug fixes, lots of great improvements to documentation, refactoring, fixes to configuration and the setup process and a commit that made the Travis build MUCH faster."

Michal Papis: "ROSSConf was amazing, an exceptional arrangement of people interested in open source. Most of rvm.io code got rewritten from Haml to Markdown. A rewrite that made rvm.io accessible. An implementation of dynamic options for Thor for RVM2 as well as an actually prototype for RVM2 was created, ARM / Raspberry PI fixes for RVM1 were implemented and a long standing issue with automatically enabling login shell in the gnome terminal got fixed."

Piotr Szotkowski: "[Eleven PRs and eight issues](https://github.com/troessner/reek/issues?q=created%3A2015-04-25..2015-04-26). Mind. Blown. A refactoring that let us remove the last ABC complexity offence in RuboCop, turning the Attribute smell much more useful for real-world scenarios, a lot of quality clean-up and debugging, making Reek a better command-line citizen, documentation examples and an Ataru integration, a nicer output nicer and a less... smelly codebase and faster Travis notifications. I can’t overstate how wonderful ROSSConf was - putting this together in such a refreshing format was an awesome idea and the lightweight, all-needs-catered-to execution was super nice."

Lisa Passing: "Since installing is the first step/ hurdle for diaspora*, that was also where most work got done. We published an updated wiki entry for setting up a dev environment on OSX Yosemite. Two people hacked on a Docker container and a Vagrant box for easier setup. Final count: 3 pull requests, two new non-trivial issues were opened and a lot of people created accounts. The whole weekend was a blast and the people and the conference were just amazing!"

Arne Brasseur: "Two people worked on a yaks-rails integration gem, one on continued testing and fixing the README with ataru, and the fourth implemented the shorthand attribute syntax. The Rails integration is working in a rough first version, the other tasks were completed and merged the day itself. I really like how ROSSConf provides an easy entry point for people to get involved in a project. Really looking forward to seeing more ROSSConfs in the future!"

**Team**
Floor Drees
Aaron Cruz
Sebastian Gräßl
Laura Gaetano
Shelly Coen
Ramon Huidobro

**Location**

**Tickets** (embedded)

**Code of Conduct**
Take from last edition

**Partners**

**Footer**
Take from last edition
- link to the Vienna / 'home' site

**Comment by ShellyCoen** [comment]
You don't waste time!

**Comment by FloorD** [comment]
^ @bastilian in case you need some copy.

**Comment by bastilian** [comment]
In order to accommodate further events i am more in favor of the rossconf.io/EVENT-CITY/EVENT-YEAR(/EVENT-MONTH)

This way we can keep everything in one repo and organisers can add their events via middleman data files and assets.

I've just setup codeship to deploy to github pages on a push/merge to master, that way there is no hassle with manual deploy. They are still possible though.

**Comment by FloorD** [comment]
:sparkling_heart: :bowtie:

**Comment by bastilian** [comment]
http://rossconf.io/event/berlin.html is online.
