### ISSUE TITLE
images have different heights

### ISSUE THREAD

**Issue by alicetragedy** [rossconf/rossconf.io#23]
The city images on the landing page now have different heights, screenshot below. ¯_(css)_/¯

![screen shot 2015-05-28 at 11 05 23](https://cloud.githubusercontent.com/assets/3143348/7856488/c7bde688-0529-11e5-9f52-0c17d06decf7.png)

**Comment by bastilian** [comment]
"fixed" with 8904d3ad2cc6043bfe50cb3b9c15326d040a2b0e 

looks like this now:
![screen shot 2015-08-08 at 09 35 51](https://cloud.githubusercontent.com/assets/7757/9149580/0bf89a90-3db1-11e5-99b2-f82a806967b1.png)
