### ISSUE TITLE
Mobile view needs improvement

### ISSUE THREAD

**Issue by sareg0** [rossconf/rossconf.io#28]
![img_3272](https://cloud.githubusercontent.com/assets/1307818/9306278/90647ee6-44f7-11e5-90c7-ce42829718d9.PNG)
![img_3273](https://cloud.githubusercontent.com/assets/1307818/9306279/907e8836-44f7-11e5-9b76-3cd82d493528.PNG)

Just the front page. I can take care of doing this.

**Comment by bastilian** [comment]
Can this be closed as #29 is merged?

**Comment by sareg0** [comment]
Yes sorry about that

**Comment by bastilian** [comment]
@sareg0 no worries. thought maybe you had more in mind to improve. :)
