### ISSUE TITLE
Simple design to ship the site

### ISSUE THREAD

**Issue by mraaroncruz** [rossconf/rossconf.io#3]
I started working on a very simple design. I don't want to dump any more time into it if you have plans already for a designer. I was thinking it could be something we could put up until we have a better design. Or just keep it depending on priorities and if no one hates it.

So, should I keep going with this or are there other plans?

![foo](http://note.io/1EGev1K)

**Comment by mraaroncruz** [comment]
forgot the logo...

**Comment by FloorD** [comment]
Other than the logo we have no design so please go ahead with this (looks great to me), I will work on the copy tomorrow and filling the team section etc etc!

**Comment by mraaroncruz** [comment]
Here is something I would like to start on tomorrow. Let me know any breaking changes, besides that, we can tweak it after it is up. We need to ship this thing. @FloorD @bastilian @alicetragedy @ramonh 
Link because it will probably look super weird here.  https://www.dropbox.com/s/kpxcokbnleem1mc/mockup.png?dl=0

Nevermind, I can't get dropbox to display it here :(
If anyone else can, add it below.
Thank you!

**Comment by bastilian** [comment]
Like it! I'll point the domain to GH-pages today so as soon as the CNAME is correct it'll be online. (will also give DNS access to @pferdefleisch and @FloorD

**Comment by FloorD** [comment]
:+1: like it too, the pastels are maybe sometimes a little hard to read (white/yellow on blue) but otherwise: SHIP EET. Thank you @pferdefleisch

**Comment by bastilian** [comment]
domain is pointed to GH

**Comment by alicetragedy** [comment]
agree about the hard to read stuff on the blue background like @FloorD said (but maybe it's just because the mockup image is also super small).
Also how would you feel about making the header image b/w so the logo is more prominent? Just my 2 cents. Looks great otherwise :+1:

**Comment by alicetragedy** [comment]
Also, double thumbs up for using Hipster Ipsum for the text @pferdefleisch. I like!

**Comment by mraaroncruz** [comment]
@alicetragedy you need to download it, that is just a small sample image @FloorD

![foo](http://cl.ly/image/1m3p391C0i2j/mockup.png)

**Comment by mraaroncruz** [comment]
tried to paste again. i need to use cloudapp or skitch. wurst. i will try to get it up by tomorrow night. could you give me the eventbrite embed code @floord

**Comment by alicetragedy** [comment]
@pferdefleisch yep, realised after my comment that I could download it. ooops. :p

**Comment by mraaroncruz** [comment]
I will change the colors to the colors in the logo at the top and find contrasty enough text.

**Comment by FloorD** [comment]
`<div style="width:100%; text-align:left;" ><iframe  src="//eventbrite.co.uk/tickets-external?eid=16138980124&ref=etckt" frameborder="0" height="214" width="100%" vspace="0" hspace="0" marginheight="5" marginwidth="5" scrolling="auto" allowtransparency="true"></iframe><div style="font-family:Helvetica, Arial; font-size:10px; padding:5px 0 5px; margin:2px; width:100%; text-align:left;" ><a style="color:#ddd; text-decoration:none;" target="_blank" href="http://www.eventbrite.co.uk/r/etckt">Event registration</a><span style="color:#ddd;"> for </span><a style="color:#ddd; text-decoration:none;" target="_blank" href="https://www.eventbrite.co.uk/e/ross-conf-tickets-16138980124?ref=etckt">ROSS Conf</a> <span style="color:#ddd;">powered by</span> <a style="color:#ddd; text-decoration:none;" target="_blank" href="http://www.eventbrite.co.uk?ref=etckt">Eventbrite</a></div></div>`

**Comment by mraaroncruz** [comment]
The price is in dollars.

Do you think we should have a link to tickets or embed it like on http://foodhack.wirsing.io?

If embed, could you send me the embed code from eventbrite in backticks (so source code) here or would you rather just add it to the site after I have the first version up?

**Comment by FloorD** [comment]
Refresh and you'll see I added the backticks. Was snoozing before. Embedded = great.

**Comment by mraaroncruz** [comment]
:shipit:
