### ISSUE TITLE
#3 London

### ISSUE THREAD

**Issue by bastilian** [rossconf/rossconf.io#35]
Date: ?
Location: ?
Sponsors: ?
Team: ?
Projects: ?

**Comment by beanieboi** [comment]
is there a wishlist for other cities?

**Comment by alicetragedy** [comment]
@beanieboi not reaaaally.. but the plan is to have people organise their own ;) We'll set something up asap so you have something to work with! ✨

**Comment by FloorD** [comment]
I'd like a Rotterdam one, Summer 2016 @beanieboi :)
